name: Actions github
on: push
jobs:
  simple-actions:
    runs-on: ubuntu-latest
    outputs:
      values: ${{ steps.action.outputs.time_greet }}
    steps:
      - uses: actions/checkout@v4
      - name: execute action
        id: action
        uses: ././actions/actions.yml
        with:
          greets: Nelson
      - name: Print greet time
        run: echo ${{ steps.action.outputs.time_greet }}
      - name: Logs ENV variables
        run: echo ${{ steps.action.outputs.HELLO_TIME }}
