name: Call Reusable
on: push
jobs:
  call-reusable:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: call reusable workflow
        uses: ./.github/workflows/reusable.yml
        with:
          name: "Nelson"
          secrets: "secret"
          executed: true
