name: Checkout
on:
  push:
    branches-ignore: main
jobs:
  checkout-test-again:
    name: Checkout action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
