name: Events
on:
  push:
    paths:
      - "**.js"
  issues:
    types: [assigned, closed, opened, reopened]
  pull_request:
    types: [assigned, synchronize, reopened, opened, closed]
jobs:
  push_event:
    runs-on: ubuntu-latest
    name: push_event
    steps:
      - name: Echo
        run: |
          echo "${{ github.sha }}"
          echo "${{ github.ref }}"
          echo "${{ github.repository }}"
