name: Manually Triggered
on:
  workflow_dispatch:
    inputs:
      strings:
        description: This is a description for workflow Manually Triggered
        type: string
        required: true
        default: "This is a default value"
      number:
        description: A number input
        default: 4
        type: number
      option:
        description: "An Options Input"
        required: true
        default: "Option 3"
        type: choice
        options:
          - Option 1
          - Option 2
          - Option 3
      boolean:
        description: A boolean option
        required: false
        type: boolean
      environment:
        description: "Environment"
        type: environment
        required: true
jobs:
  manually-trigger:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.ref }}"
      - run: |
          echo "String: ${{ inputs.strings }}"
          echo "Boolean: ${{ inputs.boolean }}"
          echo "Enviroment: ${{ inputs.environment }}"
          echo "Number: ${{ inputs.number }}"
          echo "Option: ${{ inputs.option }}"
