name: Reusable
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: false
        default: "N"
      secrets:
        type: string
        required: true
        description: This is a secret
      executed:
        required: false
        type: boolean
        default: true
    outputs:
      value:
        value: ${{ jobs.reusable.outputs.value  }}

jobs:
  reusable:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.output-step.outcome.output-step }}
    steps:
      - name: run-name
        run: |
          echo "This workflow has been executed by: ${{ inputs.name }}"
          echo "Secret: ${{ inputs.secrets }}"
          echo "Next actions: ${{ inputs.executed }}"
      - name: Optional
        if: inputs.executed
        run: |
          echo "This is a opcioanal steps"
      - name: outputs
        id: output-step
        run: echo "output-step=success" >> $GITHUB_OUTPUT
