name: Reusable
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: false
        default: "N"
      secrets:
        type: string
        required: true
        description: This is a secret
      executed:
        required: false
        type: boolean
        default: true
    outputs:
      value:
        value: ${{ jobs.nested-workflow-call.outputs.outcome  }}
        description: This is a output
    secrets:
      any-secret:
        required: true
        description: This is a secret

jobs:
  nested-workflow-call:
    uses: ./.github/workflows/reusable-output.yml
    with:
      secrets: ${{ inputs.secrets }}
      executed: ${{ inputs.executed }}
      name: ${{ inputs.name }}
